global using Xunit;
global using FluentAssertions;
global using Moq;
global using AutoFixture;
global using AutoFixture.Xunit2;
global using RunAsAdminTool.Models;
global using RunAsAdminTool.Services;
global using RunAsAdminTool.Services.Interfaces;
global using RunAsAdminTool.Tests.Helpers;